// Generated by CoffeeScript 1.6.3
(function() {
  var watch, _;

  watch = require("node-watch");

  _ = require("lodash");

  module.exports = {
    watchFiles: function(filePaths, callback) {
      if (_.isArray(filePaths)) {
        return _.each(filePaths, function(filePath) {
          return watch(filePath, callback);
        });
      } else {
        return watch(filePaths, callback);
      }
    }
  };

}).call(this);
