// Generated by CoffeeScript 1.6.3
(function() {
  var _;

  _ = require('lodash');

  module.exports = {
    isVerbose: false,
    info: function(log) {
      return console.log(_.isFunction(log) ? log() : log);
    },
    verbose: function(log) {
      if (this.verbose) {
        return this.info(log);
      }
    }
  };

}).call(this);
